apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: zookeeper-volume
  labels:
    app: zookeeper
    name: zookeeper
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"