apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    component: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      protocol: TCP
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP