kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-config
  labels:
    app: kafka
    name: kafka
data:
  server.properties: |-
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/bitnami/kafka/data
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    default.replication.factor=3
    transaction.state.log.min.isr=2
    min.insync.replicas=1
    metadata.replication.factor=3
    log.retention.hours=168
    log.retention.check.interval.ms=300000
    zookeeper.connect=zookeeper-0.zookeeper:2181
    zookeeper.connection.timeout.ms=18000
    group.initial.rebalance.delay.ms=0
    listeners=PLAINTEXT://:9092
    auto.create.topics.enable=true
