apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres-volume"
  labels:
    app: "postgres"
    name: "postgres"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"