apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    component: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP