apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  labels:
    app: media-topology
    component: media-topology
  name: media-topology
spec:
  replicas: 3
  selector:
    matchLabels:
      name: media-topology
  serviceName: media-topology
  template:
    metadata:
      labels:
        name: media-topology
        app: media-topology
    spec:
      containers:
        - name: media-topology
          image: registry.paas.psnc.pl/ecloud-poc/kafka-streams-kafka-app:latest
          command: [ "sh", "-c", "java $(JVM_OPTIONS) -cp kafka-app.jar eu.europeana.cloud.topologies.MediaTopology /config/media.properties" ]
          env:
            - name: JVM_OPTIONS
              value: "--add-opens java.base/java.lang=ALL-UNNAMED \
                            --add-opens java.base/java.util.stream=ALL-UNNAMED \
                            --add-opens java.base/java.util=ALL-UNNAMED \
                             --add-opens java.base/java.time=ALL-UNNAMED \
                             --add-opens java.base/java.net=ALL-UNNAMED \
                             --add-opens java.base/java.util.concurrent=ALL-UNNAMED \
                             --add-opens java.xml/jdk.xml.internal=ALL-UNNAMED"
          volumeMounts:
            - mountPath: /config
              name: media-topology-config-volume
          resources:
            limits:
              cpu: "900m"
              memory: 2Gi
            requests:
              cpu: "450m"
              memory: 1500Mi
      volumes:
        - name: media-topology-config-volume
          configMap:
            name: media-topology-config