apiVersion: v1
kind: Service
metadata:
  name: connect
  labels:
    app: connect
    component: connect
spec:
  clusterIP: None
  ports:
    - port: 8083
      protocol: TCP
  selector:
    app: connect
  sessionAffinity: None
  type: ClusterIP