kind: ConfigMap
apiVersion: v1
metadata:
  name: enrichment-topology-config
  labels:
    app: enrichment-topology
    name: enrichment-topology
data:
  enrichment.properties: |-
    KAFKA_HOSTS=kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092
    DB_ADDRESS=postgres-0.postgres
    DB_PORT=5432
    DB_NAME=poc-db
    DB_USER=postgres
    DB_PASSWORD=postgres
    DEREFERENCE_SERVICE_URL=https://metis-dereference-rest.test.eanadev.org/
    ENTITY_MANAGEMENT_URL=https://entity-management-production.eanadev.org/entity
    ENTITY_API_URL=https://entity-api-v2-production.eanadev.org/entity
    ENTITY_API_KEY=api2demo